apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: sakshiv22/game-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80